Table Users {
  id_users serial [pk]
  username varchar [unique]
  email varchar
  contrasena varchar(10)
}
Table Planes {
  id_planes   int
  nombre_planes varchar
  precio_usd  decimal
}
Table Suscripciones {
  id_suscripciones  int
  usuario_id  int
  plan        int
  fecha_inicio date
  fecha_fin   date
}
Table Pagos {
  id_pagos       int
  suscripcion_id int
  monto_usd   decimal
  estado      varchar
  pagado_en   timestamp
}
Table EstadoPago {
  id_estado_pago  int
  completado varchar
}
Table Perfiles {
  id_perfiles         int
  usuario_id  int
  nombre_perfil      varchar
  edad        int
  idioma      varchar
  historial   varchar

}
Table Titulos {
  id_titulos          int
  nombre_titulo       varchar
  tipo                varchar   // película o serie
  generos             varchar
  sinopsis            text
  ano_estreno         int
}
Table Tipos {
  id_tipos  int
  peliculas varchar
  series    varchar
}
Table Peliculas {
  id_peliculas int
  nombre      varchar
  generos    varchar
  duracion   time
}
Table Serie {
  id_serie        int
  titulo_id      int
  temporada       int
  numero          int
  nombre          varchar
  generos        varchar
}
Table Generos {
  id_generos int
  terror   varchar
  accion   varchar
  romance varchar
  anime varchar
  risa varchar
  documentales varchar
}
Table Historial {
  id_historial          int
  titulo_id   int
  episodio_id int
  visto_en   varchar
}

Ref: Users.id_users < Planes.nombre_planes
Ref: Planes.nombre_planes < Suscripciones.plan
Ref: Suscripciones.id_suscripciones < Pagos.id_pagos
Ref: Pagos.plan < EstadoPago.completado
Ref: EstadoPago.completado < Perfiles.id_perfiles
Ref: Perfiles.id_perfiles < Titulos.id_titulos
Ref: Titulos.id_titulos < Tipos.id_tipos
Ref: Tipos.id_tipos < Peliculas.id_peliculas
Ref: Tipos.id_tipos < Serie.id_serie
Ref: Titulos.id_titulos < Generos.id_generos
Ref: Peliculas.id_peliculas < Generos.id_generos
Ref: Serie.id_serie < Generos.id_generos
Ref: Generos.id_generos < Historial.id_historial