Table Users {
    id_Users serial [pk]
    username varchar [unique]
    email varchar
    contrasena varchar(10)
}
Table Planes {
  id_Planes   int
  nombre      varchar
  precio_usd  decimal
}
Table Suscripciones {
  id_Suscripciones  int
  Usuario_id  int
  Plan_id     int
  Fecha_inicio date
  Fecha_fin   date
}
Table Pagos {
  id_Pagos       int
  Suscripcion_id int
  monto_usd   decimal
  estado      varchar
  pagado_en   timestamp
}
Table EstadoPago {
    id_EstadoPago  int
    Completado varchar
    Fallido varchar
}
Table Perfiles {
  id_Perfiles         int
  Usuario_id  int
  Nombre      varchar
  Edad        int
  Idioma      varchar
  Historial   varchar

}
Table Titulos {
  id_Titulos          int
  Nombre      varchar
  Tipo       varchar   // película o serie
  Generos varchar
  Sinopsis    text
  Ano_estreno int
}
Table Tipos {
    id_Tipos  int
    Peliculas varchar
    Series varchar
}
Table Peliculas {
    id_Peliculas int
    Nombre varchar
    Generos varchar
    Duracion time
}
Table Serie {
  id_Serie        int
  Titulo_id   int
  Temporada   int
  Numero      int
  Nombre      varchar
  Generos    varchar
}
Table Generos {
  id_Generos int
  Terror   varchar
  Accion   varchar
  Romance varchar
  Anime varchar
  Risa varchar
  Documentales varchar
}
Table Historial {
  id_Historial          int
  Titulo_id   int
  Episodio_id int
  Visto_en   varchar
}

Ref: Users.id_Users < Planes.id_Planes
Ref: Planes.id_Planes < Suscripciones.id_Suscripciones
Ref: Suscripciones.id_Suscripciones < Pagos.id_Pagos
Ref: Pagos.estado < EstadoPago.id_EstadoPago
Ref: EstadoPago.fallido < Pagos.id_Pagos
Ref: EstadoPago.Completado < Perfiles.id_Perfiles
Ref: Perfiles.id_Perfiles < Titulos.id_Titulos
Ref: Titulos.id_Titulos < Tipos.id_Tipos
Ref: Tipos.id_Tipos < Peliculas.id_Peliculas
Ref: Tipos.id_Tipos < Serie.id_Serie
Ref: Titulos.id_Titulos < Generos.id_Generos
Ref: Peliculas.id_Peliculas < Generos.id_Generos
Ref: Serie.id_Serie < Generos.id_Generos
Ref: Generos.id_Generos < Historial.id_Historial
Ref: Perfiles.id_Perfiles < Historial.id_Historial
